use_gpu: True
device: 0
early_stop:
  patience: 100
seed: 12345
federate:
  mode: standalone
  method: Ditto
  total_round_num: 500
  client_num: 50
  sample_client_rate: 0.2
data:
  root: data/
  type: femnist
  splits: [0.6,0.2,0.2]
  subsample: 0.05
  transform: [['ToTensor'], ['Normalize', {'mean': [0.9637], 'std': [0.1592]}]]
dataloader:
  batch_size: 64
model:
  type: convnet2
  hidden: 2048
  out_channels: 62
  dropout: 0.0
train:
  local_update_steps: 3
  batch_or_epoch: epoch
  optimizer:
    lr: 0.5
    weight_decay: 0.0
grad:
  grad_clip: 5.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 10
  metrics: ['acc', 'correct', 'avg_loss']
personalization:
  regular_weight: 0.1
outdir: exp\dittoGANDP1
expname: dittoGANDP1
nbafl: 
  use: True
  mu: 0.01
  epsilon: 1
  constant: 1
  w_clip: 0.1
attack:
  attack_method: gan_attack
  attacker_id: 5
  target_label_ind: 3
  freq: 1
  